### ISSUE TITLE
Replace CSS files with `react-emotion`

### ISSUE THREAD

**Issue by dtinth** [dtinth/midi-instruments#4]
By putting CSS in JS, this will help achieve more cohesion in the code. I decided to use [`react-emotion`](https://emotion.sh/) because it is more lightweight.

Right now, `BeginnerChordMachine` is already implemented with [`react-emotion`](https://emotion.sh/).

**Comment by resir014** [comment]
I'll take this. Won't be able to do anything until later today, though.
