### ISSUE TITLE
Update MIDI device list when MIDI device connected/disconnected

### ISSUE THREAD

**Issue by dtinth** [dtinth/midi-instruments#7]
At the top right of the app, a list of MIDI devices is displayed.

![image](https://user-images.githubusercontent.com/193136/31096475-5676133a-a7e6-11e7-9c43-76f23f2ae0d7.png)

However, it does not update automatically (requires refreshing the page). Please help to make list of MIDI devices update on-the-fly.

**Comment by cherealnice** [comment]
Hey, I'd like to work on this!

**Comment by dtinth** [comment]
This is already done.
